# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#

version: 2
defaults: &defaults
  docker:
    - image: circleci/node:16.3.0
  working_directory: ~/3d-face
jobs:
  build-3d-face:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install Project Dependencies
          command: |
            yarn install --ignore-engines
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Build VatomInc-3D-Face
          command: npm run build
      - persist_to_workspace:
         root: ~/3d-face
         paths:
           - node_modules/*
           - lib/*
  publish-3d-face:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/3d-face
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/3d-face/.npmrc
      - run:
          name: Publish package
          command: |
            npm publish --access public
workflows:
  version: 2
  build-3d-face:
    jobs:
      - build-3d-face
      - publish-3d-face:
          requires:
            - build-3d-face
          filters:
            branches:
              only: master